@startuml



  namespace de.gematik.ti.openhealthcard.common {
    namespace exceptions.runtime {
      class de.gematik.ti.openhealthcard.common.exceptions.runtime.NotInitilizedWithContextException {
          {static} - MESSAGE : String
          {static} - serialVersionUID : long
          + NotInitilizedWithContextException()
          + NotInitilizedWithContextException()
          + NotInitilizedWithContextException()
      }
    }
  }
  

  namespace de.gematik.ti.openhealthcard.common {
    namespace exceptions.runtime {
      class de.gematik.ti.openhealthcard.common.exceptions.runtime.WrongThreadException {
          + WrongThreadException()
          + WrongThreadException()
      }
    }
  }
  










@enduml
